### PR TITLE
Add useful testing element

### PR DESCRIPTION
**Pull request by ReubenHill**
Adds a new element with integral moment nodes and point evaluation nodes on an interval cell which is very useful for sanity checking. Name is very much up for negotiation!

Linked with https://github.com/FEniCS/ufl/pull/47

### CODE REVIEW

**Comment by mscroggs** [comment]
This element looks to me to be very similar to an order 3 serendipity element on an interval (see the "interval order 3" example at the bottom of https://defelement.com/elements/serendipity.html).

Would interval serendipity make a good testing element to avoid having to add a new element?

**Comment by dham** [comment]
> This element looks to me to be very similar to an order 3 serendipity element on an interval (see the "interval order 3" example at the bottom of https://defelement.com/elements/serendipity.html).
> 
> Would interval serendipity make a good testing element to avoid having to add a new element?

I don't really understand the sense in which there are interval serendipity elements that are different from P elements. I mean you can make different nodal choices, but it's still a complete cubic space. It's not like the higher dimensional cases where serendipity is an incomplete polynomial space.

**Comment by mscroggs** [comment]
Serendipity elements use point evaluations on the vertices, and integral moments with polynomials on edges (and faces and volumes). (At least, this is how [Arnold and Awanou](https://arxiv.org/pdf/1101.0645.pdf) define serendipity elements. It appears that FIAT currently has a point evaluation based alternative.)

**Comment by rckirby** [comment]
This is not a serendipity element (what elements did we remove from the span to reduce dimensionality?  That question doesn't work in 1d).  It's just P3 with alternate degrees of freedom.  `P3Moments` or something like that would be fine.

**Comment by mscroggs** [comment]
In the Arnold and Awanou paper linked above, the define serendipity for general dimension n (definition 2.1). About 3/4 down page 3 they note that when n=1, the space S_n = P_n = Q_n. Hence for n=1, the version of serendipity they define is P3 with alternate degrees of freedom (the same degrees of freedom as this element once a choice of polynomials to take the moments with is decided).

**Comment by ReubenHill** [comment]
I've decided to move this into the test itself and not create a public element (see https://github.com/firedrakeproject/firedrake/pull/1971) so will close this.

**Pull request closed without merging**
